import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#F8FAFC' },
    blueHeader: { backgroundColor: '#4F46E5', padding: 20, paddingTop: 50, flexDirection: 'row', alignItems: 'center', borderBottomLeftRadius: 32, borderBottomRightRadius: 32, paddingBottom: 40 },
    headerInfo: { flex: 1, paddingHorizontal: 15 },
    headerTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
    headerSubtitle: { color: '#E0E7FF', fontSize: 12 },
    backBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.2)', justifyContent: 'center', alignItems: 'center' },
    monthPicker: { backgroundColor: 'rgba(255,255,255,0.2)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, flexDirection: 'row', alignItems: 'center' },
    monthText: { color: '#fff', fontSize: 12 },
    content: { padding: 16 },
    summaryRow: { flexDirection: 'row', gap: 10, marginBottom: 20, marginTop: -30 },
    summaryCard: { flex: 1, padding: 12, borderRadius: 20, elevation: 4 },
    sumLabel: { color: '#fff', fontSize: 10, opacity: 0.8 },
    sumValue: { color: '#fff', fontSize: 16, fontWeight: 'bold', marginTop: 4 },
    whiteCard: { backgroundColor: '#fff', padding: 20, borderRadius: 24, marginBottom: 20, elevation: 2 },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    cardTitle: { fontSize: 16, fontWeight: 'bold', color: '#1E293B' },
    badgeText: { fontSize: 12, color: '#6366F1', backgroundColor: '#EEF2FF', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10 },
    mainProgressBg: { height: 12, backgroundColor: '#F1F5F9', borderRadius: 6, marginVertical: 15, overflow: 'hidden' },
    mainProgressFill: { height: '100%', backgroundColor: '#6366F1', borderRadius: 6 },
    categoryProgressRow: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
    catLabel: { width: 70, fontSize: 12, color: '#475569' },
    miniBarBg: { flex: 1, height: 6, backgroundColor: '#F1F5F9', borderRadius: 3, marginHorizontal: 10, overflow: 'hidden' },
    miniBarFill: { height: '100%', borderRadius: 3 },
    catPercent: { width: 30, fontSize: 12, color: '#64748B', textAlign: 'right' },
    sectionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, marginTop: 10 },
    sectionTitle: { fontSize: 16, fontWeight: 'bold', color: '#1E2937' },
    countBadge: { backgroundColor: '#FEE2E2', width: 20, height: 20, borderRadius: 10, justifyContent: 'center', alignItems: 'center', marginLeft: 8 },
    countText: { color: '#EF4444', fontSize: 12, fontWeight: 'bold' },
    alertCard: { padding: 16, borderRadius: 20, borderLeftWidth: 4, marginBottom: 10 },
    alertText: { fontWeight: 'bold', color: '#991B1B' },
    alertSub: { fontSize: 12, color: '#EF4444', marginTop: 4 },
    suggestionCard: { flexDirection: 'row', backgroundColor: '#F0FDF4', padding: 16, borderRadius: 20, alignItems: 'center', gap: 12 },
    suggestIcon: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#10B981', justifyContent: 'center', alignItems: 'center' },
    suggestTitle: { fontSize: 14, color: '#065F46', fontWeight: '500' },
    suggestAmount: { fontSize: 12, color: '#10B981', marginTop: 2 },
});